// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	userdata "github.com/impr0ver/gophKeeper/internal/userdata"
	mock "github.com/stretchr/testify/mock"
)

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: userID
func (_m *Authenticator) CreateToken(userID userdata.UserID) (userdata.AuthToken, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 userdata.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(userdata.UserID) (userdata.AuthToken, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(userdata.UserID) userdata.AuthToken); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(userdata.AuthToken)
	}

	if rf, ok := ret.Get(1).(func(userdata.UserID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: token
func (_m *Authenticator) ValidateToken(token userdata.AuthToken) (userdata.UserID, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 userdata.UserID
	var r1 error
	if rf, ok := ret.Get(0).(func(userdata.AuthToken) (userdata.UserID, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(userdata.AuthToken) userdata.UserID); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(userdata.UserID)
	}

	if rf, ok := ret.Get(1).(func(userdata.AuthToken) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticator creates a new instance of Authenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticator {
	mock := &Authenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
