// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	userdata "github.com/impr0ver/gophKeeper/internal/userdata"
)

// ServerHandlers is an autogenerated mock type for the ServerHandlers type
type ServerHandlers struct {
	mock.Mock
}

// CreateRecord provides a mock function with given fields: ctx, record
func (_m *ServerHandlers) CreateRecord(ctx context.Context, record userdata.Record) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, userdata.Record) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: credentials
func (_m *ServerHandlers) CreateUser(credentials userdata.UserCredentials) (userdata.AuthToken, error) {
	ret := _m.Called(credentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 userdata.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(userdata.UserCredentials) (userdata.AuthToken, error)); ok {
		return rf(credentials)
	}
	if rf, ok := ret.Get(0).(func(userdata.UserCredentials) userdata.AuthToken); ok {
		r0 = rf(credentials)
	} else {
		r0 = ret.Get(0).(userdata.AuthToken)
	}

	if rf, ok := ret.Get(1).(func(userdata.UserCredentials) error); ok {
		r1 = rf(credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRecord provides a mock function with given fields: ctx, recordID
func (_m *ServerHandlers) DeleteRecord(ctx context.Context, recordID string) error {
	ret := _m.Called(ctx, recordID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, recordID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRecord provides a mock function with given fields: ctx, recordID
func (_m *ServerHandlers) GetRecord(ctx context.Context, recordID string) (userdata.Record, error) {
	ret := _m.Called(ctx, recordID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 userdata.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (userdata.Record, error)); ok {
		return rf(ctx, recordID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) userdata.Record); ok {
		r0 = rf(ctx, recordID)
	} else {
		r0 = ret.Get(0).(userdata.Record)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, recordID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecordsInfo provides a mock function with given fields: ctx
func (_m *ServerHandlers) GetRecordsInfo(ctx context.Context) ([]userdata.Record, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRecordsInfo")
	}

	var r0 []userdata.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]userdata.Record, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []userdata.Record); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userdata.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginUser provides a mock function with given fields: credentials
func (_m *ServerHandlers) LoginUser(credentials userdata.UserCredentials) (userdata.AuthToken, error) {
	ret := _m.Called(credentials)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 userdata.AuthToken
	var r1 error
	if rf, ok := ret.Get(0).(func(userdata.UserCredentials) (userdata.AuthToken, error)); ok {
		return rf(credentials)
	}
	if rf, ok := ret.Get(0).(func(userdata.UserCredentials) userdata.AuthToken); ok {
		r0 = rf(credentials)
	} else {
		r0 = ret.Get(0).(userdata.AuthToken)
	}

	if rf, ok := ret.Get(1).(func(userdata.UserCredentials) error); ok {
		r1 = rf(credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServerHandlers creates a new instance of ServerHandlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerHandlers {
	mock := &ServerHandlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
